# Copy this entire block to Streamlit Cloud secrets section
# Replace the placeholder values with your actual credentials

REDSHIFT_HOST = "dataeng-prod.cqyxh8rl6vlx.us-west-2.redshift.amazonaws.com"
REDSHIFT_DATABASE = "your_database_name"
REDSHIFT_USERNAME = "your_username"
REDSHIFT_PASSWORD = "your_password"
REDSHIFT_PORT = "5439"
OPENAI_API_KEY = "your_openai_api_key_here"
VPN_REQUIRED = false
ALLOWED_NETWORKS = ["0.0.0.0/0"]
PRODUCTION_MODE = true
STREAMLIT_CLOUD = true
