# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud secrets section

# Database Configuration
REDSHIFT_HOST = "dataeng-prod.cqyxh8rl6vlx.us-west-2.redshift.amazonaws.com"
REDSHIFT_DATABASE = "your_database_name"
REDSHIFT_USERNAME = "your_username"
REDSHIFT_PASSWORD = "your_password"
REDSHIFT_PORT = "5439"

# API Configuration
OPENAI_API_KEY = "your_openai_api_key_here"

# VPN and Network Configuration
VPN_REQUIRED = false
ALLOWED_NETWORKS = ["0.0.0.0/0"]

# Production Configuration
PRODUCTION_MODE = true
STREAMLIT_CLOUD = true
